source = $HOME/.config/hypr/mocha.conf

# $accent = $mauve
# $accentAlpha = $mauveAlpha
#
$accent = $maroon
$accentAlpha = $maroonAlpha

$font = Hack Nerd Font Regular
$fontColor = rgba(200, 200, 200, 1.0)

# GENERAL
general {
  hide_cursor = true
}

# BACKGROUND
background {
  monitor =
  # path = $HOME/megasync/wallpapers/buddhism/cbeaf7dajw1eiw22hodd8j21hc0u01kx.jpg
  # path = $HOME/.config/hypr/background.jpg
  path = /tmp/hyprlock_lockscreen.jpg
  blur_passes = 0
  color = $base
}

# TIME
label {
  monitor =
  text = cmd[update:1000] echo "$(date +"%H:%M")"
  color = $fontColor
  font_size = 120
  font_family = $font
  position = 30, 60
  halign = left
  valign = bottom
}

# DATE
label {
  monitor =
  text = cmd[update:43200000] date +"%A, %d %B %Y"
  color = $fontColor
  font_size = 25
  font_family = $font
  position = 50, 40
  halign = left
  valign = bottom
}

# USER AVATAR
image {
  monitor =
  path = $HOME/.face
  size = 100
  border_color = $accent
  position = 0, 75
  halign = center
  valign = center
}

# WEATHER AND AIR QUALITY
label {
    monitor =
    # cmd[update:ms] command
    # Updates every 30 minutes (1800000ms) or on unlock
    text = cmd[update:1800000] $HOME/.config/bar-modules/weather-and-air-quality.sh
    color = rgba(255, 255, 255, 1.0)
    font_size = 30
    font_family = Hack Nerd Font Mono
    position = 0, 100
    halign = center
    valign = bottom
}

# INPUT FIELD
input-field {
  monitor =
  size = 300, 60
  outline_thickness = 4
  dots_size = 0.2
  dots_spacing = 0.2
  dots_center = true
  outer_color = $accent
  inner_color = $surface0
  font_color = $text
  fade_on_empty = false
  placeholder_text = <span foreground="##$textAlpha"><i>󰌾 Logged in as </i><span foreground="##$accentAlpha">$USER</span></span>
  hide_input = false
  check_color = $accent
  fail_color = $red
  fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
  capslock_color = $yellow
  position = 0, -47
  halign = center
  valign = center
}
