---
- name: apply configuration
  hosts: new_installation

  tasks:
    - name: set global DNS defaults for all network connections
      ansible.builtin.copy:
        dest: /etc/NetworkManager/conf.d/99-global-dns.conf
        mode: "0644"
        content: |
          [connection]
          ipv4.ignore-auto-dns=yes
          ipv6.ignore-auto-dns=yes

          ipv4.dns=1.1.1.1;8.8.8.8;8.8.4.4;
          ipv6.dns=2606:4700:4700::1111;2001:4860:4860::8888;
      become: yes
      notify: restart NetworkManager

    - name: create /etc/environment for Fcitx5
      ansible.builtin.blockinfile:
        path: /etc/environment
        marker: "# {mark} ANSIBLE MANAGED BLOCK - FCITX5"
        block: |
          GTK_IM_MODULE=fcitx
          QT_IM_MODULE=fcitx
          XMODIFIERS=@im=fcitx
          SDL_IM_MODULE=fcitx
      become: yes

    - name: create /usr/lib/systemd/system-sleep/kbd-backlight.sh
      ansible.builtin.copy:
        dest: /usr/lib/systemd/system-sleep/kbd-backlight.sh
        mode: "0755"
        content: |
          #!/bin/sh

          # $1 is the phase: "pre" (going to sleep) or "post" (waking up)
          # $2 is the mode: "suspend", "hibernate", etc.

          if [ "$1" = "post" ]; then
              brightnessctl -d 'tpacpi::kbd_backlight' s 1
          fi
      become: yes

    - name: clone or pull configs repository
      ansible.builtin.git:
        repo: "https://github.com/tenetko/configs"
        dest: "/home/{{ ansible_user }}/configs"
        update: yes

    - name: create a link to Alacritty config
      ansible.builtin.file:
        src: "/home/{{ ansible_user }}/configs/alacritty"
        dest: "/home/{{ ansible_user }}/.config/alacritty"
        state: link

    - name: create a link to bar modules
      ansible.builtin.file:
        src: "/home/{{ ansible_user }}/configs/bar-modules"
        dest: "/home/{{ ansible_user }}/.config/bar-modules"
        state: link

    - name: create a link to Dunst config
      ansible.builtin.file:
        src: "/home/{{ ansible_user }}/configs/dunst"
        dest: "/home/{{ ansible_user }}/.config/dunst"
        state: link

    - name: create a link to feh config
      ansible.builtin.file:
        src: "/home/{{ ansible_user }}/configs/feh"
        dest: "/home/{{ ansible_user }}/.config/feh"
        state: link

    - name: create a link to Fuzzel config
      ansible.builtin.file:
        src: "/home/{{ ansible_user }}/configs/fuzzel"
        dest: "/home/{{ ansible_user }}/.config/fuzzel"
        state: link

    - name: create a link to Gammastep config
      ansible.builtin.file:
        src: "/home/{{ ansible_user }}/configs/gammastep"
        dest: "/home/{{ ansible_user }}/.config/gammastep"
        state: link

    - name: create a link to hyprlock config
      ansible.builtin.file:
        src: "/home/{{ ansible_user }}/configs/hypr"
        dest: "/home/{{ ansible_user }}/.config/hypr"
        state: link

    - name: create a link to imv config
      ansible.builtin.file:
        src: "/home/{{ ansible_user }}/configs/imv"
        dest: "/home/{{ ansible_user }}/.config/imv"
        state: link

    - name: check if /etc/keyd exists
      ansible.builtin.stat:
        path: /etc/keyd
      register: keyd

    - name: delete /etc/keyd only if it is a directory and not a symlink
      ansible.builtin.file:
        path: /etc/keyd
        state: absent
      become: yes
      when: keyd.stat.isdir is defined and keyd.stat.isdir

    - name: create a link to Keyd config
      ansible.builtin.file:
        src: "/home/{{ ansible_user }}/configs/keyd"
        dest: /etc/keyd
        owner: root
        group: root
        state: link
      become: yes

    - name: create a link to Kitty config
      ansible.builtin.file:
        src: "/home/{{ ansible_user }}/configs/kitty"
        dest: "/home/{{ ansible_user }}/.config/kitty"
        state: link

    - name: create a link to Neovim + Lazyvim configs
      ansible.builtin.file:
        src: "/home/{{ ansible_user }}/configs/nvim"
        dest: "/home/{{ ansible_user }}/.config/nvim"
        state: link

    - name: create a link to Starship config
      ansible.builtin.file:
        src: "/home/{{ ansible_user }}/configs/starship/starship.toml"
        dest: "/home/{{ ansible_user }}/.config/starship.toml"
        state: link

    - name: create a link to Sway config
      ansible.builtin.file:
        src: "/home/{{ ansible_user }}/configs/sway"
        dest: "/home/{{ ansible_user }}/.config/sway"
        state: link

    - name: create a link to Waybar config
      ansible.builtin.file:
        src: "/home/{{ ansible_user }}/configs/waybar"
        dest: "/home/{{ ansible_user }}/.config/waybar"
        state: link

    - name: create a link to Zshrc config
      ansible.builtin.file:
        src: "/home/{{ ansible_user }}/configs/zsh/.zshrc"
        dest: "/home/{{ ansible_user }}/.zshrc"
        state: link

    - name: set SDDM theme
      community.general.ini_file:
        path: /etc/sddm.conf
        section: Theme
        option: Current
        value: catppuccin-mocha
        # value: sugar-candy
      become: yes

    - name: set system to boot into graphical target
      ansible.builtin.file:
        src: /usr/lib/systemd/system/graphical.target
        dest: /etc/systemd/system/default.target
        state: link
      become: yes

    - name: create Megasync directory
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/megasync"
        state: directory
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_gid }}"
        mode: "0700"

    - name: set zsh as default shell
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        shell: /bin/zsh
      become: yes

    - name: enable Wayland screen sharing for Zoom
      community.general.ini_file:
        path: "~/.config/zoomus.conf"
        section: General
        option: enableWaylandShare
        value: "true"
        create: yes
        mode: "0644"

    - name: add user to libvirt group
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        groups: libvirt
        append: yes
      become: yes

    - name: create wireplumber.conf.d directory
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/.config/wireplumber/wireplumber.conf.d"
        state: directory
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_gid }}"
        mode: "0700"

    - name: set Wireplumber settings for Logitech C920 microphone
      ansible.builtin.copy:
        dest: /home/{{ ansible_user }}/.config/wireplumber/wireplumber.conf.d/51-c920-mic.conf
        mode: "0644"
        content: |
          monitor.alsa.rules =[
            {
              matches =[
                {
                  "node.name" = "~alsa_input.usb-046d_HD_Pro_Webcam_C920.*"
                }
              ]
              actions = {
                update-props = {
                  "audio.rate" = 16000
                }
              }
            }
          ]
      notify:
        - restart pipewire
        - restart wireplumber

  handlers:
    - name: restart NetworkManager
      ansible.builtin.service:
        name: NetworkManager
        state: restarted
      become: yes

    - name: restart pipewire
      ansible.builtin.systemd:
        name: pipewire
        state: restarted
        scope: user
        daemon_reload: yes
      become: no
      environment:
        XDG_RUNTIME_DIR: "/run/user/{{ ansible_user_uid }}"

    - name: restart wireplumber
      ansible.builtin.systemd:
        name: wireplumber
        state: restarted
        scope: user
        daemon_reload: yes
      become: no
      environment:
        XDG_RUNTIME_DIR: "/run/user/{{ ansible_user_uid }}"
