---
- name: install sway
  hosts: new_installation
  become: yes

  vars:
    sway:
      - fuzzel
      - swappy
      - sway
      - swaybg
      - waybar

  tasks:
    - name: install sway
      ansible.builtin.dnf5:
        name: "{{ sway }}"
        state: present
      environment:
        http_proxy: http://127.0.0.1:8888
        https_proxy: http://127.0.0.1:8888

    - name: enable hyprlock COPR repository
      community.general.copr:
        name: solopasha/hyprland
        state: enabled
      environment:
        http_proxy: http://127.0.0.1:8888
        https_proxy: http://127.0.0.1:8888

    - name: install hyprlock
      ansible.builtin.dnf5:
        name: hyprlock
        state: present
      environment:
        http_proxy: http://127.0.0.1:8888
        https_proxy: http://127.0.0.1:8888

    - name: cron job for wallpaper
      ansible.builtin.cron:
        name: "rotate wallpaper"
        minute: "*/10"
        job: "/home/{{ ansible_user }} /rotate_wallpaper.sh"
      become: no
